//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rsSegip
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Persona", Namespace="http://tempuri.org/")]
    public partial class Persona : object
    {
        
        private string CIField;
        
        private string NombresField;
        
        private string PrimerApellidoField;
        
        private string SegundoApellidoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CI
        {
            get
            {
                return this.CIField;
            }
            set
            {
                this.CIField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombres
        {
            get
            {
                return this.NombresField;
            }
            set
            {
                this.NombresField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string PrimerApellido
        {
            get
            {
                return this.PrimerApellidoField;
            }
            set
            {
                this.PrimerApellidoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SegundoApellido
        {
            get
            {
                return this.SegundoApellidoField;
            }
            set
            {
                this.SegundoApellidoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="rsSegip.wsSegipSoap")]
    public interface wsSegipSoap
    {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento CI del espacio de nombres http://tempuri.org/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VerificarDatos", ReplyAction="*")]
        rsSegip.VerificarDatosResponse VerificarDatos(rsSegip.VerificarDatosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VerificarDatos", ReplyAction="*")]
        System.Threading.Tasks.Task<rsSegip.VerificarDatosResponse> VerificarDatosAsync(rsSegip.VerificarDatosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento CI del espacio de nombres http://tempuri.org/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerDatos", ReplyAction="*")]
        rsSegip.ObtenerDatosResponse ObtenerDatos(rsSegip.ObtenerDatosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerDatos", ReplyAction="*")]
        System.Threading.Tasks.Task<rsSegip.ObtenerDatosResponse> ObtenerDatosAsync(rsSegip.ObtenerDatosRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerificarDatosRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerificarDatos", Namespace="http://tempuri.org/", Order=0)]
        public rsSegip.VerificarDatosRequestBody Body;
        
        public VerificarDatosRequest()
        {
        }
        
        public VerificarDatosRequest(rsSegip.VerificarDatosRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class VerificarDatosRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CI;
        
        public VerificarDatosRequestBody()
        {
        }
        
        public VerificarDatosRequestBody(string CI)
        {
            this.CI = CI;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerificarDatosResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerificarDatosResponse", Namespace="http://tempuri.org/", Order=0)]
        public rsSegip.VerificarDatosResponseBody Body;
        
        public VerificarDatosResponse()
        {
        }
        
        public VerificarDatosResponse(rsSegip.VerificarDatosResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class VerificarDatosResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool VerificarDatosResult;
        
        public VerificarDatosResponseBody()
        {
        }
        
        public VerificarDatosResponseBody(bool VerificarDatosResult)
        {
            this.VerificarDatosResult = VerificarDatosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerDatosRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerDatos", Namespace="http://tempuri.org/", Order=0)]
        public rsSegip.ObtenerDatosRequestBody Body;
        
        public ObtenerDatosRequest()
        {
        }
        
        public ObtenerDatosRequest(rsSegip.ObtenerDatosRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerDatosRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CI;
        
        public ObtenerDatosRequestBody()
        {
        }
        
        public ObtenerDatosRequestBody(string CI)
        {
            this.CI = CI;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerDatosResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerDatosResponse", Namespace="http://tempuri.org/", Order=0)]
        public rsSegip.ObtenerDatosResponseBody Body;
        
        public ObtenerDatosResponse()
        {
        }
        
        public ObtenerDatosResponse(rsSegip.ObtenerDatosResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerDatosResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public rsSegip.Persona ObtenerDatosResult;
        
        public ObtenerDatosResponseBody()
        {
        }
        
        public ObtenerDatosResponseBody(rsSegip.Persona ObtenerDatosResult)
        {
            this.ObtenerDatosResult = ObtenerDatosResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface wsSegipSoapChannel : rsSegip.wsSegipSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class wsSegipSoapClient : System.ServiceModel.ClientBase<rsSegip.wsSegipSoap>, rsSegip.wsSegipSoap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public wsSegipSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(wsSegipSoapClient.GetBindingForEndpoint(endpointConfiguration), wsSegipSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public wsSegipSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(wsSegipSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public wsSegipSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(wsSegipSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public wsSegipSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        rsSegip.VerificarDatosResponse rsSegip.wsSegipSoap.VerificarDatos(rsSegip.VerificarDatosRequest request)
        {
            return base.Channel.VerificarDatos(request);
        }
        
        public bool VerificarDatos(string CI)
        {
            rsSegip.VerificarDatosRequest inValue = new rsSegip.VerificarDatosRequest();
            inValue.Body = new rsSegip.VerificarDatosRequestBody();
            inValue.Body.CI = CI;
            rsSegip.VerificarDatosResponse retVal = ((rsSegip.wsSegipSoap)(this)).VerificarDatos(inValue);
            return retVal.Body.VerificarDatosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<rsSegip.VerificarDatosResponse> rsSegip.wsSegipSoap.VerificarDatosAsync(rsSegip.VerificarDatosRequest request)
        {
            return base.Channel.VerificarDatosAsync(request);
        }
        
        public System.Threading.Tasks.Task<rsSegip.VerificarDatosResponse> VerificarDatosAsync(string CI)
        {
            rsSegip.VerificarDatosRequest inValue = new rsSegip.VerificarDatosRequest();
            inValue.Body = new rsSegip.VerificarDatosRequestBody();
            inValue.Body.CI = CI;
            return ((rsSegip.wsSegipSoap)(this)).VerificarDatosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        rsSegip.ObtenerDatosResponse rsSegip.wsSegipSoap.ObtenerDatos(rsSegip.ObtenerDatosRequest request)
        {
            return base.Channel.ObtenerDatos(request);
        }
        
        public rsSegip.Persona ObtenerDatos(string CI)
        {
            rsSegip.ObtenerDatosRequest inValue = new rsSegip.ObtenerDatosRequest();
            inValue.Body = new rsSegip.ObtenerDatosRequestBody();
            inValue.Body.CI = CI;
            rsSegip.ObtenerDatosResponse retVal = ((rsSegip.wsSegipSoap)(this)).ObtenerDatos(inValue);
            return retVal.Body.ObtenerDatosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<rsSegip.ObtenerDatosResponse> rsSegip.wsSegipSoap.ObtenerDatosAsync(rsSegip.ObtenerDatosRequest request)
        {
            return base.Channel.ObtenerDatosAsync(request);
        }
        
        public System.Threading.Tasks.Task<rsSegip.ObtenerDatosResponse> ObtenerDatosAsync(string CI)
        {
            rsSegip.ObtenerDatosRequest inValue = new rsSegip.ObtenerDatosRequest();
            inValue.Body = new rsSegip.ObtenerDatosRequestBody();
            inValue.Body.CI = CI;
            return ((rsSegip.wsSegipSoap)(this)).ObtenerDatosAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.wsSegipSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.wsSegipSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.wsSegipSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:55096/wsSegip.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.wsSegipSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:55096/wsSegip.asmx");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            wsSegipSoap,
            
            wsSegipSoap12,
        }
    }
}
