//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rsPagos
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Factura", Namespace="http://tempuri.org/")]
    public partial class Factura : object
    {
        
        private int IdField;
        
        private string CiField;
        
        private double MontoField;
        
        private string EstadoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Ci
        {
            get
            {
                return this.CiField;
            }
            set
            {
                this.CiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public double Monto
        {
            get
            {
                return this.MontoField;
            }
            set
            {
                this.MontoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="rsPagos.wsPagosSoap")]
    public interface wsPagosSoap
    {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ci del espacio de nombres http://tempuri.org/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultarDeudas", ReplyAction="*")]
        rsPagos.ConsultarDeudasResponse ConsultarDeudas(rsPagos.ConsultarDeudasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultarDeudas", ReplyAction="*")]
        System.Threading.Tasks.Task<rsPagos.ConsultarDeudasResponse> ConsultarDeudasAsync(rsPagos.ConsultarDeudasRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento facturas del espacio de nombres http://tempuri.org/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Pagar", ReplyAction="*")]
        rsPagos.PagarResponse Pagar(rsPagos.PagarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Pagar", ReplyAction="*")]
        System.Threading.Tasks.Task<rsPagos.PagarResponse> PagarAsync(rsPagos.PagarRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarDeudasRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarDeudas", Namespace="http://tempuri.org/", Order=0)]
        public rsPagos.ConsultarDeudasRequestBody Body;
        
        public ConsultarDeudasRequest()
        {
        }
        
        public ConsultarDeudasRequest(rsPagos.ConsultarDeudasRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultarDeudasRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ci;
        
        public ConsultarDeudasRequestBody()
        {
        }
        
        public ConsultarDeudasRequestBody(string ci)
        {
            this.ci = ci;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarDeudasResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarDeudasResponse", Namespace="http://tempuri.org/", Order=0)]
        public rsPagos.ConsultarDeudasResponseBody Body;
        
        public ConsultarDeudasResponse()
        {
        }
        
        public ConsultarDeudasResponse(rsPagos.ConsultarDeudasResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultarDeudasResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public rsPagos.Factura[] ConsultarDeudasResult;
        
        public ConsultarDeudasResponseBody()
        {
        }
        
        public ConsultarDeudasResponseBody(rsPagos.Factura[] ConsultarDeudasResult)
        {
            this.ConsultarDeudasResult = ConsultarDeudasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PagarRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Pagar", Namespace="http://tempuri.org/", Order=0)]
        public rsPagos.PagarRequestBody Body;
        
        public PagarRequest()
        {
        }
        
        public PagarRequest(rsPagos.PagarRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PagarRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public rsPagos.Factura[] facturas;
        
        public PagarRequestBody()
        {
        }
        
        public PagarRequestBody(rsPagos.Factura[] facturas)
        {
            this.facturas = facturas;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PagarResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PagarResponse", Namespace="http://tempuri.org/", Order=0)]
        public rsPagos.PagarResponseBody Body;
        
        public PagarResponse()
        {
        }
        
        public PagarResponse(rsPagos.PagarResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class PagarResponseBody
    {
        
        public PagarResponseBody()
        {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface wsPagosSoapChannel : rsPagos.wsPagosSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class wsPagosSoapClient : System.ServiceModel.ClientBase<rsPagos.wsPagosSoap>, rsPagos.wsPagosSoap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public wsPagosSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(wsPagosSoapClient.GetBindingForEndpoint(endpointConfiguration), wsPagosSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public wsPagosSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(wsPagosSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public wsPagosSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(wsPagosSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public wsPagosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        rsPagos.ConsultarDeudasResponse rsPagos.wsPagosSoap.ConsultarDeudas(rsPagos.ConsultarDeudasRequest request)
        {
            return base.Channel.ConsultarDeudas(request);
        }
        
        public rsPagos.Factura[] ConsultarDeudas(string ci)
        {
            rsPagos.ConsultarDeudasRequest inValue = new rsPagos.ConsultarDeudasRequest();
            inValue.Body = new rsPagos.ConsultarDeudasRequestBody();
            inValue.Body.ci = ci;
            rsPagos.ConsultarDeudasResponse retVal = ((rsPagos.wsPagosSoap)(this)).ConsultarDeudas(inValue);
            return retVal.Body.ConsultarDeudasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<rsPagos.ConsultarDeudasResponse> rsPagos.wsPagosSoap.ConsultarDeudasAsync(rsPagos.ConsultarDeudasRequest request)
        {
            return base.Channel.ConsultarDeudasAsync(request);
        }
        
        public System.Threading.Tasks.Task<rsPagos.ConsultarDeudasResponse> ConsultarDeudasAsync(string ci)
        {
            rsPagos.ConsultarDeudasRequest inValue = new rsPagos.ConsultarDeudasRequest();
            inValue.Body = new rsPagos.ConsultarDeudasRequestBody();
            inValue.Body.ci = ci;
            return ((rsPagos.wsPagosSoap)(this)).ConsultarDeudasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        rsPagos.PagarResponse rsPagos.wsPagosSoap.Pagar(rsPagos.PagarRequest request)
        {
            return base.Channel.Pagar(request);
        }
        
        public void Pagar(rsPagos.Factura[] facturas)
        {
            rsPagos.PagarRequest inValue = new rsPagos.PagarRequest();
            inValue.Body = new rsPagos.PagarRequestBody();
            inValue.Body.facturas = facturas;
            rsPagos.PagarResponse retVal = ((rsPagos.wsPagosSoap)(this)).Pagar(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<rsPagos.PagarResponse> rsPagos.wsPagosSoap.PagarAsync(rsPagos.PagarRequest request)
        {
            return base.Channel.PagarAsync(request);
        }
        
        public System.Threading.Tasks.Task<rsPagos.PagarResponse> PagarAsync(rsPagos.Factura[] facturas)
        {
            rsPagos.PagarRequest inValue = new rsPagos.PagarRequest();
            inValue.Body = new rsPagos.PagarRequestBody();
            inValue.Body.facturas = facturas;
            return ((rsPagos.wsPagosSoap)(this)).PagarAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.wsPagosSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.wsPagosSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.wsPagosSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:62167/wsPagos.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.wsPagosSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:62167/wsPagos.asmx");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            wsPagosSoap,
            
            wsPagosSoap12,
        }
    }
}
